name: dev

on:
  push:
    branches:
      - develop
      - dev
  pull_request:
    branches:
      - develop
      - dev

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    permissions:
      checks: write
      contents: write
